services:
  product-service:
    build: ./product_service
    ports:
      - "8001:8000"
    networks:
      - vesnin-net
    
  order-service:
    build: ./order_service
    ports:
      - "8002:8000"
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8000
    depends_on:
      - product-service
    networks:
      - vesnin-net

networks:
  vesnin-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.10.0/24
